"""Add webhook_url and webhook_secret to App

Revision ID: f6ca9cda26f8
Revises: d4e5f6a7b8c9
Create Date: 2026-08-21 00:15:28.969959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6ca9cda26f8'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webhook_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('webhook_secret', sa.String(), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('is_live_mode',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('is_live_mode',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_column('webhook_secret')
        batch_op.drop_column('webhook_url')

    # ### end Alembic commands ###
